# variables
@baseUrl = http://sistemareserva.localhost:8080/api/v1

# health check
GET {{baseUrl}}/token

###

# get token
# @name getToken
POST  {{baseUrl}}/token
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "123"
}

###
# update profile
# @name putProfile
PUT {{baseUrl}}/profile/368e06c1-d4c5-40a7-9c85-d69a03de87d7
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIFMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM5MzE4MDQsImV4cCI6MTc1MzkzNTQwNH0.uRlrcETiBA9qNtRKOunU6wKxLrnO34aGVJarrdaaCdo
Content-Type: application/json

{
    "name": "Administrador Sistema",
    "email": "admin@admin.com",
    "access": "administrador"
}

###
# update profile
# @name putProfilePass
PUT {{baseUrl}}/profile/368e06c1-d4c5-40a7-9c85-d69a03de87d7/password
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIFMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM5MzE4MDQsImV4cCI6MTc1MzkzNTQwNH0.uRlrcETiBA9qNtRKOunU6wKxLrnO34aGVJarrdaaCdo
Content-Type: application/json

{
    "password": "123",
    "password_old": "12345"
}

###
# get apartments
# @name getApartments
GET {{baseUrl}}/apartments  
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIFMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM5MzE4MDQsImV4cCI6MTc1MzkzNTQwNH0.uRlrcETiBA9qNtRKOunU6wKxLrnO34aGVJarrdaaCdo
Content-Type: application/json

{
    "page": 1,
    "limit": 10
}

###
# create apartment
# @name createApartment
POST {{baseUrl}}/apartments
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIFMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM5MzE4MDQsImV4cCI6MTc1MzkzNTQwNH0.uRlrcETiBA9qNtRKOunU6wKxLrnO34aGVJarrdaaCdo
Content-Type: application/json

{
    "name": "10",
    "category": "Residential",
    "active": "1",
    "description": "A beautiful new apartment.",
    "situation": "Disponivel"
}

###
# update apartment
# @name updateApartment
PUT {{baseUrl}}/apartments/f906fa24-ce66-40cc-8db1-8612d09ecf87
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIFMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM5MzE4MDQsImV4cCI6MTc1MzkzNTQwNH0.uRlrcETiBA9qNtRKOunU6wKxLrnO34aGVJarrdaaCdo
Content-Type: application/json

{
    "name": "8",
    "category": "Residential",
    "active": "1",
    "description": "A beautiful new apartment.",
    "situation": "Ocupado"
}

###
# delete apartment
# @name deleteApartment
DELETE {{baseUrl}}/apartments/f906fa24-ce66-40cc-8db1-8612d09ecf87
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIGRvIFNpc3QiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM4MjMzNjUsImV4cCI6MTc1MzgyNjk2NX0.K8ipCqgqZ3JLLfLL3ZM8j-3lNHlN5Pq4xwTWw3mkuEA      
Content-Type: application/json

{
    "id": "f906fa24-ce66-40cc-8db1-8612d09ecf87"
}

###

# get apartment by UUID
# @name getApartmentByUuid
GET {{baseUrl}}/apartments/f906fa24-ce66-40cc-8db1-8612d09ecf87
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIGRvIFNpc3QiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM4MjMzNjUsImV4cCI6MTc1MzgyNjk2NX0.K8ipCqgqZ3JLLfLL3ZM8j-3lNHlN5Pq4xwTWw3mkuEA  
Content-Type: application/json

{
    "uuid": "f906fa24-ce66-40cc-8db1-8612d09ecf87"
}

### 
# get apartaments active status
# @name getApartmentsActiveStatus
POST {{baseUrl}}/apartments/f906fa24-ce66-40cc-8db1-8612d09ecf87/active
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIFMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM5MzE4MDQsImV4cCI6MTc1MzkzNTQwNH0.uRlrcETiBA9qNtRKOunU6wKxLrnO34aGVJarrdaaCdo
Content-Type: application/json

{
    "active": "1"
}

###
# get apartments by situation
# @name getApartmentsAvailable
POST {{baseUrl}}/apartments/available
headers:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJzb24iOnsiaWQiOiIzNjhlMDZjMS1kNGM1LTQwYTctOWM4NS1kNjlhMDNkZTg3ZDciLCJjb2RlIjoiMSIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIFMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFycXVpdm9faWQiOm51bGwsImFjY2VzcyI6ImFkbWluaXN0cmFkb3IiLCJwZXNzb2FfZmlzaWNhIjpudWxsLCJhY3RpdmUiOjEsImNyZWF0ZWRfYXQiOm51bGwsInVwZGF0ZWRfYXQiOm51bGx9LCJpYXQiOjE3NTM5MzE4MDQsImV4cCI6MTc1MzkzNTQwNH0.uRlrcETiBA9qNtRKOunU6wKxLrnO34aGVJarrdaaCdo      
Content-Type: application/json

{
    "situation": "Disponivel",
    "start_date": "2025-05-01",
    "end_date": "2025-12-31"
}